### ISSUE TITLE
Force close while pressing onClickListener

### ISSUE THREAD

**Issue by slumcattt** [hasancse91/retrofit-implementation#1]
Please see the log : 
java.lang.IllegalStateException: Could not execute method for android:onClick
	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
	... 10 more
Caused by: java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #1)
    for method ApiInterface.getUserValidity
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
	at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:729)
	at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:348)
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:202)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy0.getUserValidity(Unknown Source)
	at com.hellohasan.networkcallwithretrofit.Activity.MainActivity.checkUserValidity(MainActivity.java:75)
	at com.hellohasan.networkcallwithretrofit.Activity.MainActivity.buttonClickEvent(MainActivity.java:59)
	... 12 more

**Comment by hasancse91** [comment]
sorry for unacceptable late.
did you solve the problem? @slumcattt
